### ISSUE TITLE
API Down?

### ISSUE THREAD

**Issue by NickWue** [k3min/infinigag#11]
Wenn I open http://infinigag.eu01.aws.af.cm/trending/0
there is a 404 - not found error. 

Is the API down? 
Many greetings.

**Comment by br4v0** [comment]
yes please give any response about this ?? will this go up again ??

**Comment by NickWue** [comment]
It's up again! :))

**Comment by br4v0** [comment]
oh that's great, thank you

**Comment by Anubisss** [comment]
Down again?

**Comment by terranisu** [comment]
@k3min, say something please. Will API go up?

**Comment by k3min** [comment]
It's up again :smile:

**Comment by Anubisss** [comment]
I love you dude. :heart:
