### ISSUE TITLE
The paging doesn't work

### ISSUE THREAD

**Issue by Anubisss** [k3min/infinigag#13]
The paging doesn't work.

If I request this: http://infinigag.k3min.eu/girl
I get this paging ID: axj7z9W
and this URL: http://infinigag.k3min.eu/girl/axj7z9W gives status code 400.

Same for this: http://infinigag.k3min.eu/girl/fresh/azj1d7j

Or maybe I'm doing something wrong?

**Comment by k3min** [comment]
That was something on my end. Should be fixed now :+1:

**Comment by Anubisss** [comment]
Thanks. :heart:
