### ISSUE TITLE
http://infinigag.k3min.eu/design/fresh Not Working

### ISSUE THREAD

**Issue by brian-roldan** [k3min/infinigag#17]
Hi,

Is that service still open? whenever I use it I get the JSON return below:

{"status":400,"message":"Bad Request"}

Weirdly, the http request below returns a proper JSON response:

http://infinigag.k3min.eu/

Thank you for this service!

Cheers,
Brian

**Comment by aldareth** [comment]
Hello,

I think it's because the Design section is no longer on 9GAG.

**Comment by brian-roldan** [comment]
thanks @aldareth for the reply @aldareth
