### ISSUE TITLE
Gifs referenced as pngs

### ISSUE THREAD

**Issue by davidbarton** [k3min/infinigag#7]
Current version of API is returning gif images as png references. And static gifs are of course not funny at all. So could we please filter these gifs somehow? Or return urls for actual gifs? Or is there any workaround?

**Comment by medokin** [comment]
+1

**Comment by TheRinseM** [comment]
+1

**Comment by johnpaulmanoza** [comment]
Any Update about this.? @k3min

**Comment by k3min** [comment]
This should be fixed now :smile:

**Comment by davidbarton** [comment]
Awesome <3
